#pragma once

typedef enum OperatingSystem {
    OPERATING_SYSTEM_UNKNOWN,
    OPERATING_SYSTEM_WINDOWS,
    OPERATING_SYSTEM_LINUX,
    OPERATING_SYSTEM_ANDROID,
    OPERATING_SYSTEM_IOS,
    OPERATING_SYSTEM_IOS_SIMULATOR,
    OPERATING_SYSTEM_MAC,
    OPERATING_SYSTEM_COUNT
} OperatingSystem;

#if defined(OS_WINDOWS)
    #define CURRENT_OPERATING_SYSTEM OPERATING_SYSTEM_WINDOWS;
#elif defined(OS_LINUX)
    #define CURRENT_OPERATING_SYSTEM OPERATING_SYSTEM_LINUX;
#elif defined(OS_MAC)
    #define CURRENT_OPERATING_SYSTEM OPERATING_SYSTEM_MAC;
#else
    #define CURRENT_OPERATING_SYSTEM OPERATING_SYSTEM_UNKNOWN;
#endif

#if defined(OS_WINDOWS)
    #define CURRENT_OPERATING_SYSTEM_STR "windows";
#elif defined(OS_LINUX)
    #define CURRENT_OPERATING_SYSTEM_STR "linux";
#elif defined(OS_MAC)
    #define CURRENT_OPERATING_SYSTEM_STR "mac";
#else
    #define CURRENT_OPERATING_SYSTEM_STR "unknown";
#endif